### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by DiyaGandhi16** [MLSC-BSOITR/Bootstrap-Static-Web#1]
- Add a footer at the bottom of the website
- Add the copywrite text in the footer,
- Bring the copywrite text in the middle

**Comment by abitsalihu** [comment]
Hey @DiyaGandhi16, I would like to help with this issue. :)

**Comment by Mustafa-Azad025** [comment]
Hey , Please Assign Task To Me.

**Comment by Mustafa-Azad025** [comment]
Hey @DiyaGandhi16 ,
Please Check All Fixes .

**Comment by Mustafa-Azad025** [comment]
And Please Add Hacktoberfest So That We Will Benefited.

**Comment by Shubham7350** [comment]
> And Please Add Hacktoberfest Label So That We Will Benefited.

done
